### ISSUE TITLE
As a developer I shall be able to access the time scale data through a service that returns a list

### ISSUE THREAD

**Issue by JAStrachan** [JAStrachan/AC41004-Team-12-W3rld#10]
We need a series of calls that collect the right amount of data and from the right json file. It then puts the data in a list by collecting each record in an object

**Comment by JAStrachan** [comment]
We are not using a database anymore - the javascript calls will simply work by accessing the right static json file and putting the relevant data in a list

**Comment by liampost21** [comment]
Done via pull request #27
