### ISSUE TITLE
Svg graphic does not display in edge

### ISSUE THREAD

**Issue by JAStrachan** [JAStrachan/AC41004-Team-12-W3rld#23]
Does not display the svg in edge. We think its due to security concerns edge is pernickity

**Comment by sdulley** [comment]
The graph is not broken, the SVG not displaying causes an exception that results in the graph not being displayed.

**Comment by JAStrachan** [comment]
So the flexboxes heights and widths don't seem to be the issue. We can create background colours to show that the svg is there. When comparing edge and firefox I noticed the contentDocument of the svg's were different. 
These parts in Edge are null or undefined and I think are the key to the problem
activeElement (null)
all (undefined)

**Comment by JAStrachan** [comment]
So wrld3d does not support edge officially. So this is a bug we won't fix. For future knowledge though the current build of edge (42.17134.1.0) the svg doesn't display naturally. The background shows but seemingly the contentDocument of the svg doesn't get filled in. The svg doesn't get drawn. The only way we found to fix this was moving any of the the nodes in the tree of the svg around in order of the DOM in Edge inspector. The svg suddenly gets drawn. We don't know why this is but it isn't worth our time to totally fix this.
