### ISSUE TITLE
Card doesn't shrink after closing graph

### ISSUE THREAD

**Issue by LiamRattray** [JAStrachan/AC41004-Team-12-W3rld#24]
Card width should reduce to original size after pressing button to hide graph

**Comment by LiamRattray** [comment]
When changing the card's width it causes problems with the graph

**Comment by liampost21** [comment]
Thinking about having one solid size. @LiamRattray suggested 250 pixels as a size that ensures graph is not too crushed and basic view not too empty

**Comment by JAStrachan** [comment]
This now totally works with pull request #40 , there is no funny graph errors. Just needed to destroy any previously made graphs
