### ISSUE TITLE
As a WRLD 3D engineer, I should have a base class that allows for the addition of new types of data

### ISSUE THREAD

**Issue by JAStrachan** [JAStrachan/AC41004-Team-12-W3rld#9]
Our main goal of creating a super class that child classes can inherit. Allows for different types of data to be displayed in our widget and allows custom functions to be created if necessary.

**Comment by JAStrachan** [comment]
So the base card is totally finished - how it interacts with other data is determined by the measurement class that is extensible and can have conversions depending on how the data is

**Comment by LiamRattray** [comment]
The Measurement class is used to add different data types to the markers allowing us to use their specific units, icons, and range used to calculate the icon's fill percentage. It can also be inherited to add custom functions. For instance, the Temperature class contains functions to change the units used and convert sensor data appropriately. #38
